
#ifndef CUTE_CONFIG_H
#define CUTE_CONFIG_H

#define CUTE_CONF_REGISTER_COUNT 32

#define CUTE_CONF_LOCALS_LIMIT (256-CUTE_CONF_REGISTER_COUNT)

#define CUTE_CONF_CALLSTACK_SIZE 5000

#define CUTE_CONF_DEBUG

#endif // CUTE_CONFIG_H